version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - QUEUE_MODE=redis
      - REDIS_HOST=redis
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis
      - postgres
    restart: always

  waha:
    image: devlikeapro/whatsapp-http-api
    container_name: waha
    ports:
      - "3000:3000"
    env_file:
      - waha.env
    restart: always

volumes:
  n8n_data:
  postgres_data:
