services:
  - type: web
    runtime: docker
    name: n8n-whatsapp-ia
    plan: free
    autoDeploy: true
    dockerComposeFilePath: docker-compose.yml
    envVars:
      - key: PORT
        value: "5678"
